service_name: ts-example
github_owner: traceroot-ai
github_repo_name: traceroot-sdk-ts
github_commit_hash: main
environment: development
enable_span_console_export: false
enable_log_console_export: false
token: "traceroot-********************"
