service_name: ts-example
github_owner: traceroot-ai
github_repo_name: traceroot-sdk-ts
github_commit_hash: main
environment: development
local_mode: true
enable_span_console_export: true
enable_log_console_export: true

# For AWS mode, uncomment and set these:
# local_mode: false
# token: your-traceroot-token-here
# aws_region: us-west-2 